# Generated by Django 5.2.15 on 2026-06-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='F.I.Sh. / Ф.И.О.')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon / Телефон')),
                ('category', models.CharField(choices=[('criminal', 'Jinoiy / Уголовное'), ('administrative', "Ma'muriy / Административное")], max_length=20, verbose_name="Yo'nalish / Направление")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti / Время отправки')),
                ('status', models.CharField(choices=[('new', 'Yangi / Новое'), ('in_progress', 'Jarayonda / В процессе'), ('completed', 'Yakunlangan / Завершено')], default='new', max_length=20, verbose_name='Holat / Статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Eslatma / Заметки (Faqat admin ko'radi)")),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Barcha Arizalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativeApplication',
            fields=[
            ],
            options={
                'verbose_name': "Ma'muriy yo'nalish arizasi",
                'verbose_name_plural': "2. Ma'muriy Bo'lim",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.application',),
        ),
        migrations.CreateModel(
            name='CriminalApplication',
            fields=[
            ],
            options={
                'verbose_name': "Jinoiy yo'nalish arizasi",
                'verbose_name_plural': "1. Jinoiy Bo'lim",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.application',),
        ),
    ]
