# Generated by Django 5.2.15 on 2026-06-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha / Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug (URL uchun)')),
                ('content', models.TextField(verbose_name='Matn / Содержание')),
                ('category', models.CharField(choices=[('criminal', 'Jinoiy / Уголовное'), ('administrative', "Ma'muriy / Административное"), ('civil', 'Fuqarolik / Гражданское'), ('business', 'Tadbirkorlik / Предпринимательство')], max_length=20, verbose_name='Kategoriya / Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti / Время создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilganmi / Опубликовано')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Blog (Maqolalar)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourtCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzu / Тема')),
                ('result', models.CharField(choices=[('acquitted', 'Oqlov / Оправдательный приговор'), ('cancelled', 'Jarima bekor qilindi / Штраф отменен'), ('satisfied', "Da'vo qanoatlantirildi / Иск удовлетворен")], max_length=20, verbose_name='Natija / Результат')),
                ('description', models.TextField(verbose_name='Tafsilotlar / Описание дела')),
                ('category', models.CharField(choices=[('criminal', 'Jinoiy / Уголовное'), ('administrative', "Ma'muriy / Административное"), ('civil', 'Fuqarolik / Гражданское'), ('business', 'Tadbirkorlik / Предпринимательство')], max_length=20, verbose_name="Yo'nalish / Направление")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana / Дата')),
            ],
            options={
                'verbose_name': 'Sud ishi',
                'verbose_name_plural': 'Sud Amaliyoti (Natijalar)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessApplication',
            fields=[
            ],
            options={
                'verbose_name': "Tadbirkorlik yo'nalish arizasi",
                'verbose_name_plural': "4. Tadbirkorlik Bo'lim",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.application',),
        ),
        migrations.CreateModel(
            name='CivilApplication',
            fields=[
            ],
            options={
                'verbose_name': "Fuqarolik yo'nalish arizasi",
                'verbose_name_plural': "3. Fuqarolik Bo'lim",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.application',),
        ),
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Muammo tavsifi / Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(choices=[('criminal', 'Jinoiy / Уголовное'), ('administrative', "Ma'muriy / Административное"), ('civil', 'Fuqarolik / Гражданское'), ('business', 'Tadbirkorlik va MChJ / Бизнес и ООО')], max_length=20, verbose_name="Yo'nalish / Направление"),
        ),
    ]
