# Generated by Django 5.2.15 on 2026-06-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_blogpost_courtcase_businessapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='law_article',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Modda / Статья'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='law_code',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kodeks / Кодекс'),
        ),
    ]
