# Generated by Django 5.2.15 on 2026-06-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_blogpost_law_article_blogpost_law_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(default='Murakkab huquqiy muammolarga professional yechim', max_length=255, verbose_name='Sarlavha (UZ)')),
                ('title_ru', models.CharField(default='Профессиональное решение сложных правовых вопросов', max_length=255, verbose_name='Sarlavha (RU)')),
                ('subtitle_uz', models.TextField(default='<strong>Solixov Shuxriddin Muxiddin o`g`li</strong> - 2013-yildan buyon huquq sohasida faoliyat yuritib kelayotgan, Jinoiy va ma\'muriy ishlar bo\'yicha litsenziyaga ega <span class="license-text">(LITSENZIYA Adliya vazirligining Toshkent viloyati xududiy boshqarmasi №1636252)</span> tajribali advokat. Tergov va sud jarayonlarida kafolatlangan himoya hamda murakkab nizolarga professional yechimlar.', verbose_name='Kichik sarlavha (UZ)')),
                ('subtitle_ru', models.TextField(default='<strong>Солихов Шухриддин Мухиддин угли</strong> - опытный адвокат, осуществляющий деятельность в сфере права с 2013 года, имеющий лицензию по уголовным и административным делам <span class="license-text">(ЛИЦЕНЗИЯ Ташкентского областного территориального управления Министерства юстиции №1636252)</span>. Гарантированная защита в ходе следствия и судебных процессов, а также профессиональное решение сложных споров.', verbose_name='Kichik sarlavha (RU)')),
            ],
            options={
                'verbose_name': "Hero Bo'limi Sozlamasi",
                'verbose_name_plural': "Hero Bo'limi Sozlamalari",
            },
        ),
    ]
