# Generated by Django 5.2.15 on 2026-06-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_herosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtcase',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Tafsilotlar (RU) / Описание (RU)'),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Mavzu (RU) / Тема (RU)'),
        ),
        migrations.AlterField(
            model_name='courtcase',
            name='description',
            field=models.TextField(verbose_name='Tafsilotlar (UZ) / Описание (UZ)'),
        ),
        migrations.AlterField(
            model_name='courtcase',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Mavzu (UZ) / Тема (UZ)'),
        ),
    ]
