# Generated by Django 5.2.15 on 2026-07-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_courtcase_description_ru_courtcase_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosettings',
            name='subtitle_ru',
            field=models.TextField(default='<strong>Солихов Шухриддин</strong> - опытный адвокат, осуществляющий деятельность в сфере права с 2013 года, имеющий лицензию по уголовным и административным делам <span class="license-text">(ЛИЦЕНЗИЯ Ташкентского областного территориального управления Министерства юстиции №1636252)</span>. Гарантированная защита в ходе следствия и судебных процессов, а также профессиональное решение сложных споров.', verbose_name='Kichik sarlavha (RU)'),
        ),
        migrations.AlterField(
            model_name='herosettings',
            name='subtitle_uz',
            field=models.TextField(default='<strong>Solixov Shuxriddin</strong> - 2013-yildan buyon huquq sohasida faoliyat yuritib kelayotgan, Jinoiy va ma\'muriy ishlar bo\'yicha litsenziyaga ega <span class="license-text">(LITSENZIYA Adliya vazirligining Toshkent viloyati xududiy boshqarmasi №1636252)</span> tajribali advokat. Tergov va sud jarayonlarida kafolatlangan himoya hamda murakkab nizolarga professional yechimlar.', verbose_name='Kichik sarlavha (UZ)'),
        ),
    ]
