# Generated by Django 5.2.15 on 2026-07-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_courtcase_description_ru_courtcase_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_ru',
            field=models.TextField(blank=True, default='', verbose_name='Matn (RU) / Содержание (RU)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='law_article_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Modda (RU) / Статья (RU)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='law_code_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kodeks (RU) / Кодекс (RU)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sarlavha (RU) / Заголовок (RU)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='Matn (UZ) / Содержание (UZ)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='law_article',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Modda (UZ) / Статья (UZ)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='law_code',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kodeks (UZ) / Кодекс (UZ)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha (UZ) / Заголовок (UZ)'),
        ),
        migrations.AlterField(
            model_name='herosettings',
            name='subtitle_ru',
            field=models.TextField(default='<strong>Солихов Шухриддин</strong> - опытный адвокат, осуществляющий деятельность в сфере права с 2013 года, имеющий лицензию по уголовным и административным делам <span class="license-text">(ЛИЦЕНЗИЯ Ташкентского областного территориального управления Министерства юстиции №1636252)</span>. Гарантированная защита в ходе следствия и судебных процессов, а также профессиональное решение сложных споров.', verbose_name='Kichik sarlavha (RU)'),
        ),
        migrations.AlterField(
            model_name='herosettings',
            name='subtitle_uz',
            field=models.TextField(default='<strong>Solixov Shuxriddin</strong> - 2013-yildan buyon huquq sohasida faoliyat yuritib kelayotgan, Jinoiy va ma\'muriy ishlar bo\'yicha litsenziyaga ega <span class="license-text">(LITSENZIYA Adliya vazirligining Toshkent viloyati xududiy boshqarmasi №1636252)</span> tajribali advokat. Tergov va sud jarayonlarida kafolatlangan himoya hamda murakkab nizolarga professional yechimlar.', verbose_name='Kichik sarlavha (UZ)'),
        ),
    ]
