# Generated by Django 5.2.15 on 2026-07-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_herosettings_subtitle_ru_and_more'),
        ('landing', '0006_blogpost_content_ru_blogpost_law_article_ru_and_more'),
    ]

    operations = [
    ]
