# Generated by Django 5.2.15 on 2026-07-06 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Sessiya ID')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mijoz ismi')),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mijoz telefoni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="So'nggi faollik")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Yozishmalar (Chat)',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Mijoz'), ('admin', 'Admin')], max_length=10, verbose_name='Yuboruvchi')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qildimi")),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='Sessiya')),
            ],
            options={
                'verbose_name': 'Chat xabari',
                'verbose_name_plural': 'Chat xabarlari',
                'ordering': ['created_at'],
            },
        ),
    ]
