server {
    listen 80;
    server_name arbitrium-legal.uz www.arbitrium-legal.uz;

    access_log /var/log/nginx/arbitrium-legal.access.log;
    error_log /var/log/nginx/arbitrium-legal.error.log;

    location /static/ {
        alias /var/www/websiteportfolio/landing/static/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/websiteportfolio/legal_landing.sock;
    }
}
